# Generated by Django 3.2.5 on 2022-01-10 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('key', models.CharField(choices=[('BLOCK_SIZE', 'Block size (pixels)'), ('PROJECT_FONT', 'Project title font'), ('BASELINE_COLOUR', 'Baseline cell background colour'), ('BONUS_COLOUR', 'Bonus cell background colour'), ('BORDER_COLOUR', 'Cell border colour'), ('DAY_COLOURS', 'Colours for each weekday (Monday-Sunday)'), ('BLOCK_LENGTH', 'Length of block (minutes)'), ('COMPLETION_SOUND', 'Play sound on block completion?'), ('COMPLETION_NOTIFICATION', 'Browser notification on block completion?')], max_length=32)),
                ('raw_value', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('baseline', models.PositiveIntegerField()),
                ('bonus', models.PositiveIntegerField()),
                ('rows', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.project')),
            ],
        ),
    ]
