# Generated by Django 3.2.5 on 2022-01-22 18:06

import blocks.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', blocks.models.EmailFilterUserManager()),
            ],
        ),
    ]
