# Generated by Django 3.2.5 on 2022-01-10 20:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('user', 'name')},
        ),
    ]
